### ISSUE TITLE
Inconsistency in random primitive event simulation

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#119]
**Description:**
max value is not produced ever 

<img width="431" alt="screen shot 2017-11-01 at 11 04 05 pm" src="https://user-images.githubusercontent.com/3785208/32288281-6ea97ae8-bf59-11e7-9404-a6905870288b.png">

When random primitive is used, it's not outputing max value ever 
E.g for the above setting cannot see a 3 
it was only producing 0,1,2

**Comment by Anoukh** [comment]
Random number is generated using fabricator.Alphanumeric class. Here the maximum value will not be returned since it will be the ceiling value. For example generating a float value between 0 and 3 will generate 2.9xx but never 3. This will be the case for integers also where 3 will never be returned but only 2 will be returned. IMO this is the way it should be.

**Comment by suhothayan** [comment]
Then shall we change the max and min to 
some proper names (floor and ceiling values etc ) or (from and up to) that user can understand 
and update the default values accordingly

**Comment by Anoukh** [comment]
Yes. Will use from and up to, to make it more user friendly

**Comment by suhothayan** [comment]
+1

**Comment by Anoukh** [comment]
Fixed in PR Fixed in PR wso2/carbon-analytics#564 and wso2/carbon-analytics#565
