### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by erangatl** [wso2/product-sp#163]
**Description:**
Not working on Windows, CARBON_HOME environment variable is not set correctly. 

**Suggested Labels:**
SP, Severity/Major, Type/Bug

**Affected Product Version:**
Alpha2

**OS, DB, other environment details and versions:**    
Windows

**Comment by gokul** [comment]
Even after setting the JAVA_HOME environment variable, the pack is not starting up due to H2 path issues:

`[2017-11-24 03:20:45,546] ERROR org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager} - Runtime Exception occurred while calling onAllRequiredCapabilitiesAvailable of component carbon-datasource-service com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: IO Exception: "java.io.IOException: Bad pathname"; "E:wso2sp-4.0.0-Alpha3-SNAPSHOTbin../wso2/worker/database/WSO2_CARBON_DB.mv.db" [90031-196]`

**Comment by gokul** [comment]
Tracked in https://github.com/wso2/carbon-kernel/issues/1615 also.
