### ISSUE TITLE
No streams.json file exist by default in the identity-anonymization-tool

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#495]
**Description:**
streams.json file[1] doesn't exist by default in the identity-anonymization-tool.

[1] https://docs.wso2.com/display/SP4xx/Removing+Personally+Identifiable+Information+via+the+Forget-me+Tool#RemovingPersonallyIdentifiableInformationviatheForget-meTool-Step1:Configurethestreams.jsonfile

**Affected Product Version:**
wso2sp-4.0.0-update9

**Comment by RukshiW** [comment]
This section was updated as follows to mention that the file needs to be created by the user.

"In order to identify the streams and the stream attributes with PII, you need to create this file with definitions of the relevant streams and each attribute that contains PII (Personally Identifiable Information). This file must be placed in the <SP_HOME>/wso2/tools/identity-anonymization-tool-x.x.x/conf directory. "

**Comment by pcnfernando** [comment]
For SP we don't have persisted streams therefore no need of streams.json. Updated the doc in this regards.

**Comment by chaminda** [comment]
Verified with RC2
