### ISSUE TITLE
Issue related to fully distributed deployment of siddhi query with join operation

### ISSUE THREAD

**Issue by reshmavasudevan995** [wso2/product-sp#737]
**Description:**
I have set up a 2 node worker and 1 node manager siddhi cluster.
Following is the query I tried pushing into manager. Everything seems to work fine when there is no join in the query, but in case of join as mentioned below query gets deployed in worker node but events dont seem to be satisfied.

@App:name("rule_1")
@source(
type="kafka",
topic.list="test-input-topic",
group.id="test-group",
threading.option="single.thread",
bootstrap.servers="localhost:9092",
@map(type="json"))
define stream TempStream (deviceID string,roomNo string,temp int );

@sink(
type="kafka",
topic="test-output-topic",
bootstrap.servers="localhost:9092",
@map(type="json"))
define stream OutStream (message string, message1 string, message2 double);
 
@info(name = "query1")
@dist(execGroup="group1")
from TempStream[deviceID=="rule_1" and temp>10]#window.time(5 sec)
select avg(temp) as avgTemp, roomNo, deviceID
insert all events into AvgTempStream1;
  
@info(name = "query2")
@dist(execGroup="group2")
from TempStream[deviceID=="rule_1" and temp<10]#window.time(5 sec)
select avg(temp) as avgTemp, roomNo, deviceID
insert all events into AvgTempStream2;

  
@info(name = "query3")
@dist(execGroup="group3")
from AvgTempStream1#window.length(1) as stream1 join AvgTempStream2#window.length(1) as stream2
select stream1.deviceID  as message,stream1.roomNo  as message1,  stream1.avgTemp as message2
having stream1.avgTemp>stream2.avgTemp
insert into outputStream;

@info(name = "query4")
@dist(execGroup="group4")
from AvgTempStream1[deviceID=="rule_1"]
select deviceID as message, roomNo as message1, avgTemp as message2
insert into OutStream;

*Event being passed*
{"event":{"deviceID":"rule_1","roomNo":"123","temp":12}}

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pcnfernando** [comment]
@reshmavasudevan995 While analyzing the Siddhi app you provided, I observed that for the provided input;
`{"event":{"deviceID":"rule_1","roomNo":"123","temp":12}}`

From **query1**, event will be filtered as deviceID=="rule_1" and temp>10 is matched and inserted into AvgTempStream1.

From **query2**, event will be dropped without being added to **AvgTempStream2** because  temp<10 is not matched. Input temp is 12, which is not less than 10.

**query3** will not be executed because there are no events to be joined at **AvgTempStream2**. Hence, including the join query will not affect the output from the above Siddhi app for the provided input.

**query4** will be executed and data will be populated in **OutStream**, which has a kafka-sink configured.

I tested your Siddhi app with WSO2 Stream Processor 4.3.0 distributed deployment and I was able to get an output.

I also noticed that the output streams of **query3** and **query4** are different. Hence, even though **query3** get executed, the output will not be visible because you have not defined a sink for the **outputStream**.

Also, if you have further questions, please provide the WSO2 Stream Processor version you are using, as well as the console logs from manager and 2 workers.

**Comment by Niveathika92** [comment]
Closing this as it was answered, please reopen if you have further questons
