### ISSUE TITLE
[Editor][Design View] Keyboard Shortcut Support

### ISSUE THREAD

**Issue by Niveathika92** [wso2/product-sp#746]
**Description:**
As an improvement shall we give keyboard support in the design view.
Enter -> Open configuring panel
Arrows -> Move
Delete -> delete component
Tab -> Move selection to the component in the flow if possible

As of now, we have to hover the mouse pointer and select component settings and delete.
@dnwick, @erangatl WDYT?

**Suggested Labels:**
Type/Improvement

**Comment by dnwick** [comment]
@Niveathika92 sorry I missed this. Yes we need to have key board short cuts for designer as well. To open config panel we need to come with some other combination because enter is not suitable for this purpose IMO. You need to select the component before doing any delete or open config panel. And Yes we can tab to select components. But we need to carefully design these. We will make note of these when we are making the improvements

**Comment by lasanthaS** [comment]
@AnuGayan Can we close this issue?
