### ISSUE TITLE
High CPU consumption in Editor when saving some siddhi apps

### ISSUE THREAD

**Issue by sajithshn** [wso2/product-sp#755]
**Description:**
While saving some siddhi apps after a small change such as adding a space, the editor UI consumes ~300% CPU and 1.3GB memory and stays in that state for nearly more than one minute. And recovers back automatically.

If the siddhi app is saved multiple times, in an overlapping manner (i.e., save again while it's consuming high resources) the high resource consumption does not recover.

However, it was noticed that it does not depend on the file size. This could be reproduced with even siddhi apps with just 100 lines, and it works fine for some siddhi apps with 1K lines.

**Comment by erangatl** [comment]
When a complex app is imported to editor, CPU usage goes upto 60% and decreases gradually, due to parse tree generation. 

For every keystroke change parse tree is re generated and CPU usage gets higher. Now it's been delayed with a debounce, it will wait 2 seconds from the last keystroke and initiate the parse tree generation.

Could not found any CPU usage issue when saving the app.

**Comment by tishan89** [comment]
Closing as per above comment
